name: Deploy infra/main.bicep

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCE_GROUP: default-web-westeurope
  AZURE_LOCATION: westeurope
  TEMPLATE_FILE: infra/main.bicep
  PARAMETERS_FILE: infra/main.bicepparam

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.oliitrazorweb_CLIENT_ID_4FA6 }}
          tenant-id: ${{ vars.oliitrazorweb_TENANT_ID_DD77 }}
          subscription-id: ${{ vars.oliitrazorweb_SUBSCRIPTION_ID_DD77 }}

      - name: Deploy Bicep
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment group create \
              --name "infra-${{ github.run_number }}" \
              --resource-group "${AZURE_RESOURCE_GROUP}" \
              --template-file "${TEMPLATE_FILE}" \
              --parameters "${PARAMETERS_FILE}"